DROP TABLE SECTION_ENROLLMENT CASCADE CONSTRAINTS;

CREATE TABLE SECTION_ENROLLMENT (
       STUDENT_ID           NUMBER NOT NULL,
       YEAR                 NUMBER(4) NOT NULL,
       TERM_ID              NUMBER(3) NOT NULL,
       COURSE_PREFIX        VARCHAR2(4) NOT NULL,
       COURSE_NUMBER        VARCHAR2(5) NOT NULL,
       CAMPUS_ID            VARCHAR2(20) NOT NULL,
       COURSE_SUFFIX        CHAR(2) NOT NULL,
       SECTION_ID           NUMBER NOT NULL,
       STUDENT_STATUS       VARCHAR2(20) NULL,
       CONSTRAINT SECTION_ENROLLMENT_PK 
              PRIMARY KEY (STUDENT_ID, YEAR, TERM_ID, COURSE_PREFIX, 
              COURSE_NUMBER, CAMPUS_ID, COURSE_SUFFIX, SECTION_ID)
);


DROP TABLE COURSE_ENROLLMENT CASCADE CONSTRAINTS;

CREATE TABLE COURSE_ENROLLMENT (
       STUDENT_ID           NUMBER NOT NULL,
       YEAR                 NUMBER(4) NOT NULL,
       TERM_ID              NUMBER(3) NOT NULL,
       COURSE_PREFIX        VARCHAR2(4) NOT NULL,
       COURSE_NUMBER        VARCHAR2(5) NOT NULL,
       CAMPUS_ID            VARCHAR2(20) NOT NULL,
       GRADE                CHAR(3) NULL
                                   CONSTRAINT VALID_GRADE
                                          CHECK (GRADE IN ('A', 'B', 'C', 'D', 'F', 'I', 'W')),
       GRADE_INDEX          NUMBER(5,3) NULL
                                   CONSTRAINT VALID_INDEX
                                          CHECK (GRADE_INDEX BETWEEN 0 AND 4),
       CREDIT_HOURS         NUMBER NULL
                                   CONSTRAINT CREDIT_HRS_GE_ZERO
                                          CHECK (CREDIT_HOURS >= 0),
       CONSTRAINT COURSE_ENROLLMENT_PK 
              PRIMARY KEY (STUDENT_ID, YEAR, TERM_ID, COURSE_PREFIX, 
              COURSE_NUMBER, CAMPUS_ID)
);


DROP TABLE COURSE_SECTION CASCADE CONSTRAINTS;

CREATE TABLE COURSE_SECTION (
       YEAR                 NUMBER(4) NOT NULL,
       TERM_ID              NUMBER(3) NOT NULL,
       COURSE_PREFIX        VARCHAR2(4) NOT NULL,
       COURSE_NUMBER        VARCHAR2(5) NOT NULL,
       CAMPUS_ID            VARCHAR2(20) NOT NULL,
       COURSE_SUFFIX        CHAR(2) NOT NULL,
       SECTION_ID           NUMBER NOT NULL,
       INSTRUCTOR_ID        NUMBER NULL,
       DAYS_OF_WEEK         VARCHAR2(7) NULL,
       START_TIME           DATE NULL,
       END_TIME             DATE NULL,
       BUILDING             CHAR(4) NULL,
       ROOM                 CHAR(5) NULL,
       MAXIMUM_ENROLLMENT   NUMBER NULL
                                   CONSTRAINT MAX_ENROLL_GE_ZERO
                                          CHECK (MAXIMUM_ENROLLMENT >= 0),
       CONSTRAINT COURSE_SECTION_PK 
              PRIMARY KEY (YEAR, TERM_ID, COURSE_PREFIX, COURSE_NUMBER, 
              CAMPUS_ID, COURSE_SUFFIX, SECTION_ID)
);


DROP TABLE COURSE_OFFERING CASCADE CONSTRAINTS;

CREATE TABLE COURSE_OFFERING (
       YEAR                 NUMBER(4) NOT NULL,
       TERM_ID              NUMBER(3) NOT NULL,
       COURSE_PREFIX        VARCHAR2(4) NOT NULL,
       COURSE_NUMBER        VARCHAR2(5) NOT NULL,
       CAMPUS_ID            VARCHAR2(20) NOT NULL,
       PATTERN              VARCHAR2(20) NULL,
       RESTRICTIONS         VARCHAR2(2000) NULL,
       START_DATE           DATE NULL,
       END_DATE             DATE NULL,
       CONSTRAINT COURSE_OFFERING_PK 
              PRIMARY KEY (YEAR, TERM_ID, COURSE_PREFIX, 
              COURSE_NUMBER, CAMPUS_ID)
);


DROP TABLE CAMPUS CASCADE CONSTRAINTS;

CREATE TABLE CAMPUS (
       CAMPUS_ID            VARCHAR2(20) NOT NULL,
       CAMPUS_NAME          VARCHAR2(30) NULL,
       CAMPUS_ADDRESS       VARCHAR2(50) NULL,
       CAMPUS_PHONE         VARCHAR2(20) NULL,
       CONSTRAINT CAMPUS_PK 
              PRIMARY KEY (CAMPUS_ID)
);


DROP TABLE COURSE CASCADE CONSTRAINTS;

CREATE TABLE COURSE (
       COURSE_PREFIX        VARCHAR2(4) NOT NULL,
       COURSE_NUMBER        VARCHAR2(5) NOT NULL,
       DESCRIPTION          VARCHAR2(2000) NULL,
       CREDITS              NUMBER NULL
                                   CONSTRAINT CREDITS_GE_ZERO
                                          CHECK (CREDITS >= 0),
       EQUIV_COURSE_PREFIX  VARCHAR2(4) NULL,
       EQUIV_COURSE_NUMBER  VARCHAR2(5) NULL,
       CONSTRAINT COURSE_PK 
              PRIMARY KEY (COURSE_PREFIX, COURSE_NUMBER)
);


DROP TABLE TERM_ENROLLMENT CASCADE CONSTRAINTS;

CREATE TABLE TERM_ENROLLMENT (
       STUDENT_ID           NUMBER NOT NULL,
       YEAR                 NUMBER(4) NOT NULL,
       TERM_ID              NUMBER(3) NOT NULL,
       SEMESTER_INDEX       NUMBER(5,3) NULL
                                   CONSTRAINT VALID_SEMESTER_INDEX
                                          CHECK (SEMESTER_INDEX BETWEEN 0 AND 4),
       MAJOR_INDEX          NUMBER(5,3) NULL
                                   CONSTRAINT VALID_MAJOR_INDEX
                                          CHECK (MAJOR_INDEX BETWEEN 0 AND 4),
       CUMULATIVE_GPA       NUMBER(5,3) NULL
                                   CONSTRAINT VALID_CUMM_GPA
                                          CHECK (CUMULATIVE_GPA BETWEEN 0 AND 4),
       CONSTRAINT TERM_ENROLLMENT_PK 
              PRIMARY KEY (STUDENT_ID, YEAR, TERM_ID)
);


DROP TABLE STUDENT CASCADE CONSTRAINTS;

CREATE TABLE STUDENT (
       STUDENT_ID           NUMBER NOT NULL,
       NAME                 VARCHAR2(30) NULL,
       LOCAL_ADDRESS        VARCHAR2(50) NULL,
       LOCAL_PHONE          VARCHAR2(20) NULL,
       DEPARTMENT_ID        VARCHAR2(4) NULL,
       CONSTRAINT STUDENT_PK 
              PRIMARY KEY (STUDENT_ID)
);


DROP TABLE INSTRUCTOR CASCADE CONSTRAINTS;

CREATE TABLE INSTRUCTOR (
       INSTRUCTOR_ID        NUMBER NOT NULL,
       INSTRUCTOR_NAME      VARCHAR2(30) NULL,
       DEPARTMENT_ID        VARCHAR2(4) NULL,
       OFFICE               VARCHAR2(20) NULL,
       PHONE                VARCHAR2(20) NULL,
       CONSTRAINT INSTRUCTOR_PK 
              PRIMARY KEY (INSTRUCTOR_ID)
);


DROP TABLE DEPARTMENT CASCADE CONSTRAINTS;

CREATE TABLE DEPARTMENT (
       DEPARTMENT_ID        VARCHAR2(4) NOT NULL,
       NAME                 VARCHAR2(30) NULL,
       ADDRESS              VARCHAR2(50) NULL,
       PHONE                VARCHAR2(20) NULL,
       CONSTRAINT DEPARTMENT_PK 
              PRIMARY KEY (DEPARTMENT_ID)
);


DROP TABLE TERM CASCADE CONSTRAINTS;

CREATE TABLE TERM (
       YEAR                 NUMBER(4) NOT NULL,
       TERM_ID              NUMBER(3) NOT NULL,
       START_DATE           DATE NULL,
       END_DATE             DATE NULL,
       CONSTRAINT TERM_PK 
              PRIMARY KEY (YEAR, TERM_ID)
);


ALTER TABLE SECTION_ENROLLMENT
       ADD  ( CONSTRAINT SECTION_ENR_COURSE_SECTION_FK
              FOREIGN KEY (YEAR, TERM_ID, COURSE_PREFIX, COURSE_NUMBER, 
			CAMPUS_ID, COURSE_SUFFIX, SECTION_ID)
                             REFERENCES COURSE_SECTION
                             ON DELETE CASCADE ) ;


ALTER TABLE SECTION_ENROLLMENT
       ADD  ( CONSTRAINT SECTION_ENR_COURSE_ENROLL_FK
              FOREIGN KEY (STUDENT_ID, YEAR, TERM_ID, COURSE_PREFIX, 
              COURSE_NUMBER, CAMPUS_ID)
                             REFERENCES COURSE_ENROLLMENT ) ;


ALTER TABLE COURSE_ENROLLMENT
       ADD  ( CONSTRAINT COURSE_ENROLL_OFFERING_FK
              FOREIGN KEY (YEAR, TERM_ID, COURSE_PREFIX, 
              COURSE_NUMBER, CAMPUS_ID)
                             REFERENCES COURSE_OFFERING
                             ON DELETE CASCADE ) ;


ALTER TABLE COURSE_ENROLLMENT
       ADD  ( CONSTRAINT COURSE_ENROLL_TERM_ENROLL_FK
              FOREIGN KEY (STUDENT_ID, YEAR, TERM_ID)
                             REFERENCES TERM_ENROLLMENT ) ;


ALTER TABLE COURSE_SECTION
       ADD  ( CONSTRAINT COURSE_SECTION_INSTRUCTOR_FK
              FOREIGN KEY (INSTRUCTOR_ID)
                             REFERENCES INSTRUCTOR ) ;


ALTER TABLE COURSE_SECTION
       ADD  ( CONSTRAINT COURSE_SECTION_OFFERING_FK
              FOREIGN KEY (YEAR, TERM_ID, COURSE_PREFIX, 
              COURSE_NUMBER, CAMPUS_ID)
                             REFERENCES COURSE_OFFERING
                             ON DELETE CASCADE ) ;


ALTER TABLE COURSE_OFFERING
       ADD  ( CONSTRAINT COURSE_OFFERING_CAMPUS_FK
              FOREIGN KEY (CAMPUS_ID)
                             REFERENCES CAMPUS ) ;


ALTER TABLE COURSE_OFFERING
       ADD  ( CONSTRAINT COURSE_OFFERING_TERM_FK
              FOREIGN KEY (YEAR, TERM_ID)
                             REFERENCES TERM ) ;


ALTER TABLE COURSE_OFFERING
       ADD  ( CONSTRAINT COURSE_OFFERING_COURSE_FK
              FOREIGN KEY (COURSE_PREFIX, COURSE_NUMBER)
                             REFERENCES COURSE ) ;


ALTER TABLE COURSE
       ADD  ( CONSTRAINT COURSE_DEPARTMENT_FK
              FOREIGN KEY (COURSE_PREFIX)
                             REFERENCES DEPARTMENT ) ;


ALTER TABLE COURSE
       ADD  ( CONSTRAINT EQUIVALENT_COURSE_FK
              FOREIGN KEY (EQUIV_COURSE_PREFIX, EQUIV_COURSE_NUMBER)
                             REFERENCES COURSE ) ;


ALTER TABLE TERM_ENROLLMENT
       ADD  ( CONSTRAINT TERM_ENROLLMENT_STUDENT_FK
              FOREIGN KEY (STUDENT_ID)
                             REFERENCES STUDENT ) ;


ALTER TABLE TERM_ENROLLMENT
       ADD  ( CONSTRAINT TERM_ENROLLMENT_TERM_FK
              FOREIGN KEY (YEAR, TERM_ID)
                             REFERENCES TERM ) ;


ALTER TABLE STUDENT
       ADD  ( CONSTRAINT STUDENT_DEPARTMENT_FK
              FOREIGN KEY (DEPARTMENT_ID)
                             REFERENCES DEPARTMENT ) ;


ALTER TABLE INSTRUCTOR
       ADD  ( CONSTRAINT INSTRUCTOR_DEPARTMENT_FK
              FOREIGN KEY (DEPARTMENT_ID)
                             REFERENCES DEPARTMENT ) ;
